FROM node:24-alpine AS deps
LABEL authors="bjankov"
WORKDIR /app
COPY package*.json ./
RUN npm ci --omit=dev

FROM node:24-alpine AS dev
RUN apk update && apk upgrade --no-cache
WORKDIR /app
ENV NODE_ENV=development
COPY package*.json ./
RUN npm ci
COPY src ./src
USER node
EXPOSE 8080
CMD ["npm", "run", "dev"]

FROM alpine:latest AS runtime
RUN apk update && apk upgrade --no-cache \
    && apk add --no-cache libstdc++ libgcc \
    && addgroup -g 1000 node \
    && adduser -u 1000 -G node -s /bin/sh -D node

WORKDIR /app
ENV NODE_ENV=production
COPY --from=deps /usr/local/bin/node /usr/local/bin/
COPY --from=deps --chown=node:node /app/node_modules ./node_modules
COPY --chown=node:node package*.json ./
COPY --chown=node:node src ./src
USER node
EXPOSE 8080
CMD ["node", "src/server.js"]